# Docker Compose configuration for the holiday API service with health check and network settings
# latest docker or docker-compose must be available in your system to start services.
# To start the service, run: docker-compose up -d  or docker compose up -d
services:
  holiday-planner-api:
    #image: holidayplanner.example.com/api/holiday-planner-api:2.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      #- "11300:11300"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      # Comment previous line and Uncomment below line to enable JMX monitoring on port 11300 and also uncomment port mapping "11300:11300" above
      #- JAVA_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=11300 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.rmi.port=11300 -Djava.rmi.server.hostname=localhost -Xms128m -Xmx256m
      - SPRING_PROFILES_ACTIVE=prod
      # default logging level is INFO if we want to set logging to WARN then uncomment below line
      #- LOGGING_LEVEL_COM_EXAMPLE_HOLIDAYPLANNER=WARN
      - NAGER_DATE_API_URL=https://date.nager.at/api/v3/PublicHolidays/{year}/{countryCode}
      - NAGAR_AVAILABLE_COUNTRIES_API_URL=https://date.nager.at/api/v3/AvailableCountries
      - DEFAULT_NUMBER_OF_HOLIDAYS_TO_RETURN=3
      - MAX_NUMBER_OF_HOLIDAYS_CAN_BE_RETURNED=12
      - MIN_HOLIDAY_SEARCH_SUPPORTED_YEAR=1975
      - MAX_HOLIDAY_SEARCH_SUPPORTED_YEAR=2075
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/management/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - monitoring-network


networks:
  monitoring-network:
    driver: bridge